"""fix category

Revision ID: 6b0b3ffe9886
Revises: a8cad994a9c1
Create Date: 2018-12-05 00:59:01.825972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0b3ffe9886'
down_revision = 'a8cad994a9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'book_id')
    # ### end Alembic commands ###
